#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ALNC

#include "Basic.hpp"

#include "UpperBody_structs.hpp"


namespace SDK
{

// ScriptStruct ALNC.ALNC_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct ALNC::FAnimBlueprintGeneratedConstantData final : public UpperBody::FAnimBlueprintGeneratedConstantData
{
};

}

