#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_NPC_009_Jeffer_Barricade01A

#include "Basic.hpp"

#include "AnimBP_NpcBase_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AnimBP_NPC_009_Jeffer_Barricade01A.AnimBP_NPC_009_Jeffer_Barricade01A_C
// 0x0000 (0x0980 - 0x0980)
class UAnimBP_NPC_009_Jeffer_Barricade01A_C final : public UAnimBP_NpcBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBP_NPC_009_Jeffer_Barricade01A_C">();
	}
	static class UAnimBP_NPC_009_Jeffer_Barricade01A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_NPC_009_Jeffer_Barricade01A_C>();
	}
};

}

