#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_VulgusContainer

#include "Basic.hpp"

#include "AnimBP_VulgusContainer_classes.hpp"
#include "AnimBP_VulgusContainer_parameters.hpp"


namespace SDK
{

// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.ExecuteUbergraph_AnimBP_VulgusContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_VulgusContainer_C::ExecuteUbergraph_AnimBP_VulgusContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "ExecuteUbergraph_AnimBP_VulgusContainer");

	Params::AnimBP_VulgusContainer_C_ExecuteUbergraph_AnimBP_VulgusContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_E019533D446BD384B86C449829E3BCCF
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_E019533D446BD384B86C449829E3BCCF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_E019533D446BD384B86C449829E3BCCF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_79172ED44D12255C23FC65BD38E0B799
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_79172ED44D12255C23FC65BD38E0B799()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_79172ED44D12255C23FC65BD38E0B799");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_685149814019757EC2840FBF595A800F
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_685149814019757EC2840FBF595A800F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_685149814019757EC2840FBF595A800F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_4F8C610E4BDEC65CEAA032B396093162
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_4F8C610E4BDEC65CEAA032B396093162()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_4F8C610E4BDEC65CEAA032B396093162");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_43B9357F4F47474C6E3833BA1AC7ED9F
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_43B9357F4F47474C6E3833BA1AC7ED9F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_43B9357F4F47474C6E3833BA1AC7ED9F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_34BD86B548718DB5C0A97E83453889EA
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_34BD86B548718DB5C0A97E83453889EA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_34BD86B548718DB5C0A97E83453889EA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_090A481E4D2E90E4DA7A45A3F195C8C7
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_090A481E4D2E90E4DA7A45A3F195C8C7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_090A481E4D2E90E4DA7A45A3F195C8C7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_064A53074A2E2D3645F057819168CB25
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_064A53074A2E2D3645F057819168CB25()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_064A53074A2E2D3645F057819168CB25");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_VulgusContainer_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "AnimGraph");

	Params::AnimBP_VulgusContainer_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_04D46DAE4A75C34DFB980BA6BC9753C5
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_04D46DAE4A75C34DFB980BA6BC9753C5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_04D46DAE4A75C34DFB980BA6BC9753C5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_VulgusContainer.AnimBP_VulgusContainer_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_5E0842A1466A99501DE04E8E65242B05
// (BlueprintEvent)

void UAnimBP_VulgusContainer_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_5E0842A1466A99501DE04E8E65242B05()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_VulgusContainer_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_VulgusContainer_AnimGraphNode_TransitionResult_5E0842A1466A99501DE04E8E65242B05");

	UObject::ProcessEvent(Func, nullptr);
}

}

