#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Animlayer_Player_UpperBody

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function animlayer_Player_UpperBody.animlayer_Player_UpperBody_C.UpperBodyLayer
// 0x0020 (0x0020 - 0x0000)
struct Animlayer_Player_UpperBody_C_UpperBodyLayer final
{
public:
	struct FPoseLink                              InputPose;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              UpperBodyLayer_0;                                  // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function animlayer_Player_UpperBody.animlayer_Player_UpperBody_C.AimOffsetLayer
// 0x0020 (0x0020 - 0x0000)
struct Animlayer_Player_UpperBody_C_AimOffsetLayer final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              AimOffsetLayer_0;                                  // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

}

