#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AppleARKitPoseTrackingLiveLink

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "LiveLinkAnimationCore_classes.hpp"


namespace SDK
{

// Class AppleARKitPoseTrackingLiveLink.AppleARKitPoseTrackingLiveLinkRemapAsset
// 0x0068 (0x0090 - 0x0028)
class UAppleARKitPoseTrackingLiveLinkRemapAsset final : public ULiveLinkRetargetAsset
{
public:
	struct FVector                                AppleARKitHumanForward;                            // 0x0028(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                MeshForward;                                       // 0x0034(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FName, class FName>                AppleARKitBoneNamesToMeshBoneNames;                // 0x0040(0x0050)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AppleARKitPoseTrackingLiveLinkRemapAsset">();
	}
	static class UAppleARKitPoseTrackingLiveLinkRemapAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAppleARKitPoseTrackingLiveLinkRemapAsset>();
	}
};

}

