#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AR_1003

#include "Basic.hpp"

#include "AR_structs.hpp"


namespace SDK
{

// ScriptStruct AR_1003.AR_1003_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct AR_1003::FAnimBlueprintGeneratedConstantData final : public AR::FAnimBlueprintGeneratedConstantData
{
};

}

