#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CustomizeFellowPreviewStage

#include "Basic.hpp"

#include "BP_CustomizeFellowPreviewStage_classes.hpp"
#include "BP_CustomizeFellowPreviewStage_parameters.hpp"


namespace SDK
{

// Function BP_CustomizeFellowPreviewStage.BP_CustomizeFellowPreviewStage_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CustomizeFellowPreviewStage_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomizeFellowPreviewStage_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CustomizeFellowPreviewStage.BP_CustomizeFellowPreviewStage_C.ExecuteUbergraph_BP_CustomizeFellowPreviewStage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CustomizeFellowPreviewStage_C::ExecuteUbergraph_BP_CustomizeFellowPreviewStage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomizeFellowPreviewStage_C", "ExecuteUbergraph_BP_CustomizeFellowPreviewStage");

	Params::BP_CustomizeFellowPreviewStage_C_ExecuteUbergraph_BP_CustomizeFellowPreviewStage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CustomizeFellowPreviewStage.BP_CustomizeFellowPreviewStage_C.GetViewTargets
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// TArray<class AActor*>                   ReturnValue                                            (Parm, OutParm, ReturnParm)

TArray<class AActor*> ABP_CustomizeFellowPreviewStage_C::GetViewTargets() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomizeFellowPreviewStage_C", "GetViewTargets");

	Params::BP_CustomizeFellowPreviewStage_C_GetViewTargets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_CustomizeFellowPreviewStage.BP_CustomizeFellowPreviewStage_C.BP_GetCameraComponent
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UCineCameraComponent*             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UCineCameraComponent* ABP_CustomizeFellowPreviewStage_C::BP_GetCameraComponent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomizeFellowPreviewStage_C", "BP_GetCameraComponent");

	Params::BP_CustomizeFellowPreviewStage_C_BP_GetCameraComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

