#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionTarget_VulgusGenerator_Type1

#include "Basic.hpp"

#include "BP_MissionTarget_VulgusGenerator_Type1_classes.hpp"
#include "BP_MissionTarget_VulgusGenerator_Type1_parameters.hpp"


namespace SDK
{

// Function BP_MissionTarget_VulgusGenerator_Type1.BP_MissionTarget_VulgusGenerator_Type1_C.BP_GetNiagaraComponents
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EM1MissionTargetState                   MissionTargetState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class UNiagaraComponent*>        ReturnValue                                            (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UNiagaraComponent*> ABP_MissionTarget_VulgusGenerator_Type1_C::BP_GetNiagaraComponents(EM1MissionTargetState MissionTargetState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MissionTarget_VulgusGenerator_Type1_C", "BP_GetNiagaraComponents");

	Params::BP_MissionTarget_VulgusGenerator_Type1_C_BP_GetNiagaraComponents Parms{};

	Parms.MissionTargetState = MissionTargetState;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_MissionTarget_VulgusGenerator_Type1.BP_MissionTarget_VulgusGenerator_Type1_C.BP_GetAllNiagaraComponents
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UNiagaraComponent*>        ReturnValue                                            (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UNiagaraComponent*> ABP_MissionTarget_VulgusGenerator_Type1_C::BP_GetAllNiagaraComponents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MissionTarget_VulgusGenerator_Type1_C", "BP_GetAllNiagaraComponents");

	Params::BP_MissionTarget_VulgusGenerator_Type1_C_BP_GetAllNiagaraComponents Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

