#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NpcBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_NpcBase.BP_NpcBase_C.ExecuteUbergraph_BP_NpcBase
// 0x0004 (0x0004 - 0x0000)
struct BP_NpcBase_C_ExecuteUbergraph_BP_NpcBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_NpcBase.BP_NpcBase_C.BP_GetWidgetComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_NpcBase_C_BP_GetWidgetComponent final
{
public:
	class UWidgetComponent*                       ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};

// Function BP_NpcBase.BP_NpcBase_C.BP_GetInteractionComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_NpcBase_C_BP_GetInteractionComponent final
{
public:
	class UM1InteractionInvokerComponent*         ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};

}

