#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PreviewLevelShopEtc

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_PreviewLevelShopEtc.BP_PreviewLevelShopEtc_C.ExecuteUbergraph_BP_PreviewLevelShopEtc
// 0x0004 (0x0004 - 0x0000)
struct BP_PreviewLevelShopEtc_C_ExecuteUbergraph_BP_PreviewLevelShopEtc final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

