#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sack_PlainSet01_YSA

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Sack_PlainSet01_YSA.BP_Sack_PlainSet01_YSA_C
// 0x0098 (0x02E0 - 0x0248)
class ABP_Sack_PlainSet01_YSA_C final : public AM1CanTickOnClientActor
{
public:
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA212;        // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_Sack00_SM_YSA;               // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA221;        // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA11121;      // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA122;        // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA112;        // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA1112;       // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA1111;       // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA121;        // 0x0288(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA111;        // 0x0290(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA12;         // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA22;         // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA211;        // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA21;         // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA11;         // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA2;          // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA1;          // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LV_Italy_Village_Prop_GrainBag00_SM_YSA;           // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Sack_PlainSet01_YSA_C">();
	}
	static class ABP_Sack_PlainSet01_YSA_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Sack_PlainSet01_YSA_C>();
	}
};

}

