#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SimpleTaskActor_Interaction

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SimpleTaskActor_Interaction.BP_SimpleTaskActor_Interaction_C
// 0x0008 (0x04A0 - 0x0498)
class ABP_SimpleTaskActor_Interaction_C final : public AM1SimpleTaskActorInteraction
{
public:
	class UNiagaraComponent*                      InteratableAreaFx;                                 // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SimpleTaskActor_Interaction_C">();
	}
	static class ABP_SimpleTaskActor_Interaction_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SimpleTaskActor_Interaction_C>();
	}
};

}

