#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BR

#include "Basic.hpp"

#include "UpperBody_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass BR.BR_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UBR_C : public UUpperBody_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BR_C">();
	}
	static class UBR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBR_C>();
	}
};

}

