#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CalcHaileyUltraColdDamage

#include "Basic.hpp"

#include "CalcDamageBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CalcHaileyUltraColdDamage.CalcHaileyUltraColdDamage_C
// 0x0010 (0x0140 - 0x0130)
class UCalcHaileyUltraColdDamage_C final : public UCalcDamageBase_C
{
public:
	double                                        AdditionalDamageRatio;                             // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        WeaponTotalDamage;                                 // 0x0138(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DoCalculation(struct FM1AbilityOpCalcParam& Param, struct FM1CalcDamageInfo& DamageInfo) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CalcHaileyUltraColdDamage_C">();
	}
	static class UCalcHaileyUltraColdDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCalcHaileyUltraColdDamage_C>();
	}
};

}

