#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CalcTargetHPRatioDamage

#include "Basic.hpp"

#include "CalcDamageBase_classes.hpp"
#include "M1Data_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CalcTargetHPRatioDamage.CalcTargetHPRatioDamage_C
// 0x0018 (0x0148 - 0x0130)
class UCalcTargetHPRatioDamage_C final : public UCalcDamageBase_C
{
public:
	double                                        TargetHpBasedDamage;                               // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TargetNamedHpBasedDamage;                          // 0x0138(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TargetBossHpBasedDamage;                           // 0x0140(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DoCalculation(struct FM1AbilityOpCalcParam& Param, struct FM1CalcDamageInfo& DamageInfo) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CalcTargetHPRatioDamage_C">();
	}
	static class UCalcTargetHPRatioDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCalcTargetHPRatioDamage_C>();
	}
};

}

