#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraModifier_DeboneStart

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraModifier_DeboneStart.CameraModifier_DeboneStart_C
// 0x0148 (0x0190 - 0x0048)
class UCameraModifier_DeboneStart_C final : public UM1CameraModifierForPlayer
{
public:
	double                                        CameraGoalDistance;                                // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraGoalPitch;                                   // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bInitialized;                                      // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bInterrupted;                                      // 0x0059(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5A[0x2];                                       // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                PrevViewTargetLocation;                            // 0x005C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               PrevViewTargetRotation;                            // 0x0068(0x000C)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        PrevAlpha;                                         // 0x0078(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRuntimeFloatCurve                     LocationCurve;                                     // 0x0080(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FRuntimeFloatCurve                     RotationCurve;                                     // 0x0108(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void SetInterrupted();
	void Initialize(const struct FVector& InLocation, const struct FRotator& InRotation);
	void GetRotationAlpha(double* OutAlpha);
	void GetLocationAlpha(double* OutAlpha);
	void FadeCameraRotation(const struct FRotator& InViewRotation, struct FRotator* OutRotation);
	void FadeCameraLocation(const struct FVector& InViewLocation, struct FVector* OutLocation);
	void BlueprintModifyCamera(float DeltaTime, const struct FVector& ViewLocation, const struct FRotator& ViewRotation, float FOV, struct FVector* NewViewLocation, struct FRotator* NewViewRotation, float* NewFOV);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraModifier_DeboneStart_C">();
	}
	static class UCameraModifier_DeboneStart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraModifier_DeboneStart_C>();
	}
};

}

