#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraModifier_DeboneArrived

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraModifier_DeboneArrived.CameraModifier_DeboneArrived_C
// 0x0220 (0x0268 - 0x0048)
class UCameraModifier_DeboneArrived_C : public UM1CameraModifierForPlayer
{
public:
	double                                        CameraGoalDistance;                                // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CameraPitchOffset;                                 // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                BeforeViewLocation;                                // 0x0058(0x000C)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                AfterViewLocation;                                 // 0x0064(0x000C)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               BeforeViewRotation;                                // 0x0070(0x000C)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FRotator                               AfterViewRotation;                                 // 0x007C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bWasFadeIn;                                        // 0x0088(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bWasFadeOut;                                       // 0x0089(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bWasFully;                                         // 0x008A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bInterrupted;                                      // 0x008B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRuntimeFloatCurve                     FadeInCurve;                                       // 0x0090(0x0088)(Edit, BlueprintVisible, Transient, DisableEditOnInstance)
	struct FRuntimeFloatCurve                     FadeOutCurve;                                      // 0x0118(0x0088)(Edit, BlueprintVisible, Transient, DisableEditOnInstance)
	struct FRotator                               BeforeFullyCameraRotation;                         // 0x01A0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        FullyCameraRotationSpeed;                          // 0x01B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRuntimeFloatCurve                     FullyCameraRotationSpeedCurve;                     // 0x01B8(0x0088)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FFloatRange                            ClampCameraRotationRange;                          // 0x0240(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFloatRange                            CurClampCameraRotationRange;                       // 0x0250(0x0010)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bStopCameraClamp;                                  // 0x0260(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UpdateAfterViews(const struct FVector& InLocation, const struct FRotator& InRotation, struct FVector* OutLocation, struct FRotator* OutRotation);
	void StopCameraClamp(bool bStop);
	void ProcessZero(const struct FVector& InViewLocation, const struct FRotator& InViewRotation, struct FVector* OutViewLocation, struct FRotator* OutViewRotation);
	void ProcessFully(const struct FVector& InViewLocation, const struct FRotator& InViewRotation, double DeltaSeconds, struct FVector* OutViewLocation, struct FRotator* OutViewRotation);
	void ProcessFadeOut(const struct FVector& InViewLocation, const struct FRotator& InViewRotation, struct FVector* OutViewLocation, struct FRotator* OutViewRotation);
	void ProcessFadeIn(const struct FVector& InViewLocation, const struct FRotator& InViewRotation, struct FVector* OutViewLocation, struct FRotator* OutViewRotation);
	void InitFully(struct FVector* OutLocation, struct FRotator* OutRotation);
	void InitFadeOut();
	void InitFadeIn(const struct FVector& InLocation, const struct FRotator& InRotation);
	void GetCurvedAlpha(double* Float);
	void FullyCameraRotationClamp(const struct FRotator& Begin, const struct FRotator& Goal, double DeltaSeconds, struct FRotator* OutBegin, struct FRotator* OutGoal);
	void FullyCameraRotation(struct FRotator* OutRotation);
	void FullyCameraLocation(const struct FRotator& InViewRotation, struct FVector* OutLocation);
	void FadeCameraRotation(struct FRotator* OutRotation);
	void FadeCameraLocation(struct FVector* OutLocation);
	void BlueprintModifyCamera(float DeltaTime, const struct FVector& ViewLocation, const struct FRotator& ViewRotation, float FOV, struct FVector* NewViewLocation, struct FRotator* NewViewRotation, float* NewFOV);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CameraModifier_DeboneArrived_C">();
	}
	static class UCameraModifier_DeboneArrived_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraModifier_DeboneArrived_C>();
	}
};

}

