#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_HG

#include "Basic.hpp"

#include "UpperBody_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_HG.F_HG_C
// 0x0000 (0x1CD0 - 0x1CD0)
class UF_HG_C : public UUpperBody_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_HG_C">();
	}
	static class UF_HG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_HG_C>();
	}
};

}

