#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InventoryPreviewFellowAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function InventoryPreviewFellowAnimBP.InventoryPreviewFellowAnimBP_C.ExecuteUbergraph_InventoryPreviewFellowAnimBP
// 0x0004 (0x0004 - 0x0000)
struct InventoryPreviewFellowAnimBP_C_ExecuteUbergraph_InventoryPreviewFellowAnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function InventoryPreviewFellowAnimBP.InventoryPreviewFellowAnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct InventoryPreviewFellowAnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};

}

