#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NormalMonster_AOE_Spawner

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NormalMonster_AOE_Spawner.NormalMonster_AOE_Spawner_C
// 0x0030 (0x0780 - 0x0750)
class ANormalMonster_AOE_Spawner_C final : public AM1AbilityActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0750(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0758(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        InitialDelay;                                      // 0x0760(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        SpawnInterval;                                     // 0x0768(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        SpawnRandomRange;                                  // 0x0770(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SpawnCount;                                        // 0x0778(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurSpawnCount;                                     // 0x077C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SpawnHitArea();
	void Spawn_AOE();
	void FindRandomLocation2D(struct FVector* OutLocation2D);
	void FindFloorAtLocation(const struct FVector& InLocation2D, struct FVector* OutLocation);
	void ExecuteUbergraph_NormalMonster_AOE_Spawner(int32 EntryPoint);
	void BP_OnPostSpawnAbilityActor();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NormalMonster_AOE_Spawner_C">();
	}
	static class ANormalMonster_AOE_Spawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANormalMonster_AOE_Spawner_C>();
	}
};

}

