#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerDroneTransformControlValues

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// UserDefinedStruct PlayerDroneTransformControlValues.PlayerDroneTransformControlValues
// 0x0028 (0x0028 - 0x0000)
struct FPlayerDroneTransformControlValues final
{
public:
	class USceneComponent*                        Component_22_0388073041BED19535AE018AF0F338A9;     // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVectorSpringState                     LocationVectorSpringState_28_429F5B2144E0A59B359109B9C60876DF; // 0x0008(0x001C)(Edit, BlueprintVisible, NoDestructor)
};

}

