#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_AJaxActiveBase

#include "Basic.hpp"

#include "Skill_AJaxActiveBase_classes.hpp"
#include "Skill_AJaxActiveBase_parameters.hpp"


namespace SDK
{

// Function Skill_AJaxActiveBase.Skill_AJaxActiveBase_C.RefreshCommonGaugeByUsingSkill
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_AJaxActiveBase_C::RefreshCommonGaugeByUsingSkill()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxActiveBase_C", "RefreshCommonGaugeByUsingSkill");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_AJaxActiveBase.Skill_AJaxActiveBase_C.MakeSkillActivateParams
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AActor*                           InOwner                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<struct FM1AbilityParamData>      ReturnValue                                            (Parm, OutParm, ReturnParm)

TArray<struct FM1AbilityParamData> USkill_AJaxActiveBase_C::MakeSkillActivateParams(const class AActor* InOwner) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxActiveBase_C", "MakeSkillActivateParams");

	Params::Skill_AJaxActiveBase_C_MakeSkillActivateParams Parms{};

	Parms.InOwner = InOwner;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

