#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_AJaxVoidWalk

#include "Basic.hpp"

#include "Skill_AJaxVoidWalk_classes.hpp"
#include "Skill_AJaxVoidWalk_parameters.hpp"


namespace SDK
{

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnRep_bLanded
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_AJaxVoidWalk_C::OnRep_bLanded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "OnRep_bLanded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnFunctionalTest
// (Event, Protected, BlueprintEvent)

void USkill_AJaxVoidWalk_C::OnFunctionalTest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "OnFunctionalTest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnEventReceived_DD9DA59F413BC77A5A08B39466A0A34E
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_AJaxVoidWalk_C::OnEventReceived_DD9DA59F413BC77A5A08B39466A0A34E(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "OnEventReceived_DD9DA59F413BC77A5A08B39466A0A34E");

	Params::Skill_AJaxVoidWalk_C_OnEventReceived_DD9DA59F413BC77A5A08B39466A0A34E Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnCompleted_DD9DA59F413BC77A5A08B39466A0A34E
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_AJaxVoidWalk_C::OnCompleted_DD9DA59F413BC77A5A08B39466A0A34E(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "OnCompleted_DD9DA59F413BC77A5A08B39466A0A34E");

	Params::Skill_AJaxVoidWalk_C_OnCompleted_DD9DA59F413BC77A5A08B39466A0A34E Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnBlendOut_DD9DA59F413BC77A5A08B39466A0A34E
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_AJaxVoidWalk_C::OnBlendOut_DD9DA59F413BC77A5A08B39466A0A34E(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "OnBlendOut_DD9DA59F413BC77A5A08B39466A0A34E");

	Params::Skill_AJaxVoidWalk_C_OnBlendOut_DD9DA59F413BC77A5A08B39466A0A34E Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnAbilityEvent_E7F0EC3E4A2E60CA4F44C8ADCD380ED4
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_AJaxVoidWalk_C::OnAbilityEvent_E7F0EC3E4A2E60CA4F44C8ADCD380ED4(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "OnAbilityEvent_E7F0EC3E4A2E60CA4F44C8ADCD380ED4");

	Params::Skill_AJaxVoidWalk_C_OnAbilityEvent_E7F0EC3E4A2E60CA4F44C8ADCD380ED4 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnAbilityEvent_1A71391F42477386EDF9AC9097887390
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_AJaxVoidWalk_C::OnAbilityEvent_1A71391F42477386EDF9AC9097887390(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "OnAbilityEvent_1A71391F42477386EDF9AC9097887390");

	Params::Skill_AJaxVoidWalk_C_OnAbilityEvent_1A71391F42477386EDF9AC9097887390 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.InvokeStrengthenedStatusEffect
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USkill_AJaxVoidWalk_C::InvokeStrengthenedStatusEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "InvokeStrengthenedStatusEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.GetSkillMontage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     SkillMontage                                           (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USkill_AJaxVoidWalk_C::GetSkillMontage(class UAnimMontage** SkillMontage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "GetSkillMontage");

	Params::Skill_AJaxVoidWalk_C_GetSkillMontage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SkillMontage != nullptr)
		*SkillMontage = Parms.SkillMontage;
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.ExecuteUbergraph_Skill_AJaxVoidWalk
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_AJaxVoidWalk_C::ExecuteUbergraph_Skill_AJaxVoidWalk(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "ExecuteUbergraph_Skill_AJaxVoidWalk");

	Params::Skill_AJaxVoidWalk_C_ExecuteUbergraph_Skill_AJaxVoidWalk Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_AJaxVoidWalk_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "BP_OnDeactivated");

	Params::Skill_AJaxVoidWalk_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_AJaxVoidWalk_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.BP_MakePreloadAssetList
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FM1AbilityAssetPreload           OutAbilityAssetPreload                                 (Parm, OutParm)

void USkill_AJaxVoidWalk_C::BP_MakePreloadAssetList(struct FM1AbilityAssetPreload* OutAbilityAssetPreload) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_AJaxVoidWalk_C", "BP_MakePreloadAssetList");

	Params::Skill_AJaxVoidWalk_C_BP_MakePreloadAssetList Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutAbilityAssetPreload != nullptr)
		*OutAbilityAssetPreload = std::move(Parms.OutAbilityAssetPreload);
}

}

