#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_AJaxReversedDoor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Skill_AJaxActiveBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_AJaxReversedDoor.Skill_AJaxReversedDoor_C
// 0x0028 (0x0368 - 0x0340)
class USkill_AJaxReversedDoor_C final : public USkill_AJaxActiveBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        SpawnDistance;                                     // 0x0348(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bExecutedRefreshCommonGauge;                       // 0x0350(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_351[0x7];                                      // 0x0351(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           NormalMontage;                                     // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           StrengthenedMontage;                               // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void OnFunctionalTest();
	void OnEventReceived_24A373CC48ED2D68A29C179CD426F762(const struct FM1AbilityEvent& Event);
	void OnCompleted_24A373CC48ED2D68A29C179CD426F762(const struct FM1AbilityEvent& Event);
	void OnBlendOut_24A373CC48ED2D68A29C179CD426F762(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_DB0E903E448A5D5CE301B388A9810CE7(const struct FM1AbilityEvent& Event);
	void GetSkillMontage(class UAnimMontage** SkillMontage);
	void ExecuteUbergraph_Skill_AJaxReversedDoor(int32 EntryPoint);
	void BP_OnDeactivated(bool bCancelled);
	void BP_OnActivated();

	void BP_MakePreloadAssetList(struct FM1AbilityAssetPreload* OutAbilityAssetPreload) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Skill_AJaxReversedDoor_C">();
	}
	static class USkill_AJaxReversedDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_AJaxReversedDoor_C>();
	}
};

}

