#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_AJaxVoidWalk

#include "Basic.hpp"

#include "M1Data_structs.hpp"
#include "M1_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnRep_bLanded
// 0x00B0 (0x00B0 - 0x0000)
struct Skill_AJaxVoidWalk_C_OnRep_bLanded final
{
public:
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x0008(0x0008)(ConstParm, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_TryStartOperationsToSelfByTag_ReturnValue; // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13[0x5];                                       // 0x0013(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_1;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_GetSkillMontage_SkillMontage;             // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_2;              // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_FindActorsInRadius_OutActors;             // 0x0040(0x0010)(ReferenceParm)
	bool                                          CallFunc_FindActorsInRadius_ReturnValue;           // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class AActor*, struct FM1AbilityIDList>  CallFunc_InvokeAllStatusEffectToTargetsByTag_ReturnValue; // 0x0058(0x0050)()
	float                                         CallFunc_FindActorsInRadius_InRadius_ImplicitCast; // 0x00A8(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnEventReceived_DD9DA59F413BC77A5A08B39466A0A34E
// 0x0040 (0x0040 - 0x0000)
struct Skill_AJaxVoidWalk_C_OnEventReceived_DD9DA59F413BC77A5A08B39466A0A34E final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnCompleted_DD9DA59F413BC77A5A08B39466A0A34E
// 0x0040 (0x0040 - 0x0000)
struct Skill_AJaxVoidWalk_C_OnCompleted_DD9DA59F413BC77A5A08B39466A0A34E final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnBlendOut_DD9DA59F413BC77A5A08B39466A0A34E
// 0x0040 (0x0040 - 0x0000)
struct Skill_AJaxVoidWalk_C_OnBlendOut_DD9DA59F413BC77A5A08B39466A0A34E final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnAbilityEvent_E7F0EC3E4A2E60CA4F44C8ADCD380ED4
// 0x0040 (0x0040 - 0x0000)
struct Skill_AJaxVoidWalk_C_OnAbilityEvent_E7F0EC3E4A2E60CA4F44C8ADCD380ED4 final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.OnAbilityEvent_1A71391F42477386EDF9AC9097887390
// 0x0040 (0x0040 - 0x0000)
struct Skill_AJaxVoidWalk_C_OnAbilityEvent_1A71391F42477386EDF9AC9097887390 final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.InvokeStrengthenedStatusEffect
// 0x01A8 (0x01A8 - 0x0000)
struct Skill_AJaxVoidWalk_C_InvokeStrengthenedStatusEffect final
{
public:
	int32                                         PrevMaxEnergyShield;                               // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsStrengthenedSkill_ReturnValue;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityOwnerInfo                    CallFunc_GetOwnerInfo_ReturnValue;                 // 0x0008(0x0038)(ConstParm, NoDestructor, ContainsInstancedReference)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1ScaledInteger                       CallFunc_GetStatValue_ReturnValue;                 // 0x0050(0x0008)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ScaledIntToInt_ReturnValue;          // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityOwnerInfo                    CallFunc_GetOwnerInfo_ReturnValue_1;               // 0x005C(0x0038)(ConstParm, NoDestructor, ContainsInstancedReference)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetStatValue_ReturnValue_1;               // 0x00A8(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityParamData                    K2Node_MakeStruct_M1AbilityParamData;              // 0x00B0(0x0020)()
	int32                                         CallFunc_Conv_ScaledIntToInt_ReturnValue_1;        // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FM1AbilityParamData>            K2Node_MakeArray_Array;                            // 0x00D8(0x0010)(ReferenceParm)
	struct FM1AbilityOperationParam               K2Node_MakeStruct_M1AbilityOperationParam;         // 0x00E8(0x00B0)(ContainsInstancedReference)
	struct FM1AbilityId                           CallFunc_InvokeFirstStatusEffectToSelfByTag_ReturnValue; // 0x0198(0x0010)(HasGetValueTypeHash)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.GetSkillMontage
// 0x0010 (0x0010 - 0x0000)
struct Skill_AJaxVoidWalk_C_GetSkillMontage final
{
public:
	class UAnimMontage*                           SkillMontage;                                      // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsStrengthenedSkill_ReturnValue;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.ExecuteUbergraph_Skill_AJaxVoidWalk
// 0x0448 (0x0448 - 0x0000)
struct Skill_AJaxVoidWalk_C_ExecuteUbergraph_Skill_AJaxVoidWalk final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_4;                        // 0x0008(0x0040)(ConstParm)
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate;              // 0x0048(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        Temp_struct_Variable;                              // 0x0058(0x0040)()
	class UM1AbilityTask_WaitAbilityEvent*        CallFunc_WaitAbilityEvent_ReturnValue;             // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x3];                                       // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x00A4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_3;                        // 0x00B8(0x0040)(ConstParm)
	struct FM1AbilityEvent                        Temp_struct_Variable_1;                            // 0x00F8(0x0040)()
	class UM1AbilityTask_WaitAbilityEvent*        CallFunc_WaitAbilityEvent_ReturnValue_1;           // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess;   // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_2;                        // 0x0148(0x0040)(ConstParm)
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0188(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_1;                        // 0x0198(0x0040)(ConstParm)
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x01D8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event;                          // 0x01E8(0x0040)(ConstParm)
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_4;            // 0x0228(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        Temp_struct_Variable_2;                            // 0x0238(0x0040)()
	struct FM1SkillFTestTestCase                  CallFunc_MakeTestCaseStatusEffectOnMonster_ReturnValue; // 0x0278(0x0068)()
	class AM1Monster*                             CallFunc_GetTestMonster_ReturnValue;               // 0x02E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x02E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AM1Player*                              K2Node_DynamicCast_AsM1Player;                     // 0x02F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TryCommitAbility_ReturnValue;             // 0x02F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FA[0x6];                                      // 0x02FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1SkillFTestTestCase                  CallFunc_MakeTestCaseDamageOnMonster_ReturnValue;  // 0x0300(0x0068)()
	TArray<struct FM1SkillFTestTestCase>          K2Node_MakeArray_Array;                            // 0x0368(0x0010)(ReferenceParm)
	double                                        CallFunc_BreakVector_X;                            // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0380(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0388(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1SkillFTestTestCaseSheet             K2Node_MakeStruct_M1SkillFTestTestCaseSheet;       // 0x0390(0x0040)()
	class UAnimMontage*                           CallFunc_GetSkillMontage_SkillMontage;             // 0x03D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UM1AbilityTask_PlayMontageAndWait*      CallFunc_PlayMontageAndWaitForEvent_ReturnValue;   // 0x03D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x03E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bCancelled;                           // 0x03E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3E2[0x2];                                      // 0x03E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x03E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UNiagaraComponent*>              CallFunc_SpawnFXsForAbilityToTarget_ReturnValue;   // 0x03F0(0x0010)(ReferenceParm, ContainsInstancedReference)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0400(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0410(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0418(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0420(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0428(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_434[0x4];                                      // 0x0434(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_GetSkillMontage_SkillMontage_1;           // 0x0438(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_1;              // 0x0440(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.BP_OnDeactivated
// 0x0001 (0x0001 - 0x0000)
struct Skill_AJaxVoidWalk_C_BP_OnDeactivated final
{
public:
	bool                                          bCancelled;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function Skill_AJaxVoidWalk.Skill_AJaxVoidWalk_C.BP_MakePreloadAssetList
// 0x00D0 (0x00D0 - 0x0000)
struct Skill_AJaxVoidWalk_C_BP_MakePreloadAssetList final
{
public:
	struct FM1AbilityAssetPreload                 OutAbilityAssetPreload;                            // 0x0000(0x0040)(Parm, OutParm)
	struct FSoftObjectPath                        CallFunc_GetSoftObjectPath_ReturnValue;            // 0x0040(0x0020)(ZeroConstructor, HasGetValueTypeHash)
	struct FSoftObjectPath                        CallFunc_GetSoftObjectPath_ReturnValue_1;          // 0x0060(0x0020)(ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FSoftObjectPath>                K2Node_MakeArray_Array;                            // 0x0080(0x0010)(ReferenceParm)
	struct FM1AbilityAssetPreload                 K2Node_MakeStruct_M1AbilityAssetPreload;           // 0x0090(0x0040)()
};

}

