#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Gley_Passive

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Skill_Gley_Passive.Skill_Gley_Passive_C
// 0x0048 (0x0380 - 0x0338)
class USkill_Gley_Passive_C final : public UM1SkillAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FM1AbilityId                           NormalStatusEffectId;                              // 0x0340(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FM1AbilityId                           BerserkStatusEffectId;                             // 0x0350(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         FloorCount;                                        // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_364[0x4];                                      // 0x0364(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        DropRatio;                                         // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentFloorStack;                                 // 0x0370(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_374[0x4];                                      // 0x0374(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CurrentDropRatio;                                  // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnRequiemNormal(const struct FM1AbilityEvent& M1AbilityEvent);
	void OnLeaveBerserk();
	void OnFunctionalTest();
	void OnEnterBerserk();
	void OnDie(const struct FM1AbilityEvent& InAbilityEvent);
	void OnAbilityEvent_EC9DD62F4CA01D7E3D16EAB39A55ECFF(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_9E86DCB24C5789B45533DF8ECAD654F8(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_3E3358A64DE9A39BC682DDAF1C0F08B7(const struct FM1AbilityEvent& Event);
	void OnAbilityEvent_21A39BF94AD5DD48807D82A0E4BC0502(const struct FM1AbilityEvent& Event);
	void ExecuteUbergraph_Skill_Gley_Passive(int32 EntryPoint);
	void Clear();
	void BP_OnDeactivated(bool bCancelled);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Skill_Gley_Passive_C">();
	}
	static class USkill_Gley_Passive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkill_Gley_Passive_C>();
	}
};

}

