#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Gley_Active04

#include "Basic.hpp"

#include "Skill_Gley_Active04_classes.hpp"
#include "Skill_Gley_Active04_parameters.hpp"


namespace SDK
{

// Function Skill_Gley_Active04.Skill_Gley_Active04_C.OnFunctionalTest
// (Event, Protected, BlueprintEvent)

void USkill_Gley_Active04_C::OnFunctionalTest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "OnFunctionalTest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.OnBerserkModeChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bBerserk                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Gley_Active04_C::OnBerserkModeChanged(bool bBerserk)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "OnBerserkModeChanged");

	Params::Skill_Gley_Active04_C_OnBerserkModeChanged Parms{};

	Parms.bBerserk = bBerserk;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.OnActivatedAltWeapon
// (BlueprintCallable, BlueprintEvent)

void USkill_Gley_Active04_C::OnActivatedAltWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "OnActivatedAltWeapon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.OnAbilityEvent_9F2B6F0A47E9B379357AB4B9C8B4C238
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Gley_Active04_C::OnAbilityEvent_9F2B6F0A47E9B379357AB4B9C8B4C238(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "OnAbilityEvent_9F2B6F0A47E9B379357AB4B9C8B4C238");

	Params::Skill_Gley_Active04_C_OnAbilityEvent_9F2B6F0A47E9B379357AB4B9C8B4C238 Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.OnAbilityEvent_6FA8322B4B72EF31EAE830A71DC266DB
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Gley_Active04_C::OnAbilityEvent_6FA8322B4B72EF31EAE830A71DC266DB(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "OnAbilityEvent_6FA8322B4B72EF31EAE830A71DC266DB");

	Params::Skill_Gley_Active04_C_OnAbilityEvent_6FA8322B4B72EF31EAE830A71DC266DB Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.InitializeRounds
// (Public, BlueprintCallable, BlueprintEvent)

void USkill_Gley_Active04_C::InitializeRounds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "InitializeRounds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.ExecuteUbergraph_Skill_Gley_Active04
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Gley_Active04_C::ExecuteUbergraph_Skill_Gley_Active04(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "ExecuteUbergraph_Skill_Gley_Active04");

	Params::Skill_Gley_Active04_C_ExecuteUbergraph_Skill_Gley_Active04 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Gley_Active04_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "BP_OnDeactivated");

	Params::Skill_Gley_Active04_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Gley_Active04.Skill_Gley_Active04_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_Gley_Active04_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Gley_Active04_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

