#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SMG_1003

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SMG_1003.SMG_1003_C
// 0x0018 (0x0490 - 0x0478)
class ASMG_1003_C final : public AM1Weapon
{
public:
	class UM1WeaponFireLoopComponent*             M1WeaponFireLoop;                                  // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1WeaponMagazineReloadComponent*       M1WeaponMagazineReload;                            // 0x0480(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1WeaponInstantHitComponent*           M1WeaponInstantHit;                                // 0x0488(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SMG_1003_C">();
	}
	static class ASMG_1003_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASMG_1003_C>();
	}
};

}

