#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpawnPreviewActorBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SpawnPreviewActorBase.SpawnPreviewActorBase_C
// 0x0060 (0x02A8 - 0x0248)
class ASpawnPreviewActorBase_C : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_AKComponent_C*                      BP_AKComponent;                                    // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_Preview;                                        // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        MaxDistance;                                       // 0x0268(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	double                                        CollisionRadius;                                   // 0x0270(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	double                                        CollisionHalfHeight;                               // 0x0278(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FCollisionProfileName                  CollisionProfile;                                  // 0x0280(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, ExposeOnSpawn)
	bool                                          bSkipOwnerWalkableCheck;                           // 0x0288(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_289[0x7];                                      // 0x0289(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraSystem*                         PreviewVFx;                                        // 0x0290(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UAkAudioEvent*                          PreviewSFx;                                        // 0x0298(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bRotateToOwner;                                    // 0x02A0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bDebugDraw;                                        // 0x02A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bIsSpawnPointFound;                                // 0x02A2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEnableInstall;                                    // 0x02A3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void UpdateTransform(float DeltaSeconds);
	void UpdatePreviewInfo(const struct FVector& SpawnLocation, const struct FRotator& New_Transform_Rotation);
	void ReceiveBeginPlay();
	void IsSpawnPointFound(bool* Found);
	void IsSpawnable(bool* bIsSpawnable);
	bool FindSpawnPoint_Sweep(const struct FVector& Start, const struct FVector& Dir, double Dist, double Radius, bool bReverse, bool InDebugDraw, const struct FLinearColor& TraceColor, struct FHitResult* OutHit);
	void FindSpawnPoint(class AActor* Owner_0, bool bFullDetect, bool* ReturnFound, struct FVector* ReturnLoc);
	void ExecuteUbergraph_SpawnPreviewActorBase(int32 EntryPoint);
	void CalcSpawnRotation(struct FRotator* NewParam);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SpawnPreviewActorBase_C">();
	}
	static class ASpawnPreviewActorBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASpawnPreviewActorBase_C>();
	}
};

}

