#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Crosshair_008

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WB_CrosshairBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Crosshair_008.UI_Crosshair_008_C
// 0x0008 (0x0730 - 0x0728)
class UUI_Crosshair_008_C final : public UWB_CrosshairBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UI_Crosshair_008_C;                 // 0x0728(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_UI_Crosshair_008(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Crosshair_008_C">();
	}
	static class UUI_Crosshair_008_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Crosshair_008_C>();
	}
};

}

