#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_GameHP_Champion

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_GameHP_Champion.UI_GameHP_Champion_C
// 0x0040 (0x0928 - 0x08E8)
class UUI_GameHP_Champion_C final : public UM1UIMonsterInfo
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       UIAnim_Property_Open;                              // 0x08F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ANIM_Focus;                                        // 0x08F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 AdvantageIcon;                                     // 0x0900(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         Icon_Property;                                     // 0x0908(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         Panel_ElementalWeakness;                           // 0x0910(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           UI_Focus;                                          // 0x0918(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UM1WidgetSwitcher*                      WS_Marker;                                         // 0x0920(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_GameHP_Champion(int32 EntryPoint);
	void Construct();
	void BP_UpdateWeakElementalIcons(const TArray<class UTexture2D*>& WeakElementalIcons);
	void BP_UpdateWeakAdvantageIcon(class UTexture2D* WeakAdvantageIcon);
	void BP_SetSpawnedByMission(bool InByMission, bool bHidden);
	void BP_SetFocusUIVisibility(bool bVisible);
	void BP_ChangedMonsterLifeTime(float InLifeTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_GameHP_Champion_C">();
	}
	static class UUI_GameHP_Champion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_GameHP_Champion_C>();
	}
};

}

