#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Game_InstanceDungeonScore

#include "Basic.hpp"

#include "M1_structs.hpp"


namespace SDK::Params
{

// Function UI_Game_InstanceDungeonScore.UI_Game_InstanceDungeonScore_C.UISet_Default
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_InstanceDungeonScore_C_UISet_Default final
{
public:
	bool                                          bVisible;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InstanceDungeonScore.UI_Game_InstanceDungeonScore_C.OnEventWidgetOpen
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_InstanceDungeonScore_C_OnEventWidgetOpen final
{
public:
	EM1WidgetAnimDirection                        InDirection;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InstanceDungeonScore.UI_Game_InstanceDungeonScore_C.ExecuteUbergraph_UI_Game_InstanceDungeonScore
// 0x0038 (0x0038 - 0x0000)
struct UI_Game_InstanceDungeonScore_C_ExecuteUbergraph_UI_Game_InstanceDungeonScore final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bVisible;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EM1WidgetAnimDirection                        K2Node_Event_InDirection;                          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayUIAnimation_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Event_InAddScoreText;                       // 0x0020(0x0018)(ConstParm)
};

// Function UI_Game_InstanceDungeonScore.UI_Game_InstanceDungeonScore_C.BP_SetOpacityToOne
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_InstanceDungeonScore_C_BP_SetOpacityToOne final
{
public:
	bool                                          bVisible;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InstanceDungeonScore.UI_Game_InstanceDungeonScore_C.BP_SetAddScore
// 0x0018 (0x0018 - 0x0000)
struct UI_Game_InstanceDungeonScore_C_BP_SetAddScore final
{
public:
	class FText                                   InAddScoreText;                                    // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};

}

