#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Game_InvasionDungeon_TimeAttack

#include "Basic.hpp"

#include "M1_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function UI_Game_InvasionDungeon_TimeAttack.UI_Game_InvasionDungeon_TimeAttack_C.UISet_Default
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_InvasionDungeon_TimeAttack_C_UISet_Default final
{
public:
	bool                                          Set_Visible;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InvasionDungeon_TimeAttack.UI_Game_InvasionDungeon_TimeAttack_C.OnEventWidgetOpen
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_InvasionDungeon_TimeAttack_C_OnEventWidgetOpen final
{
public:
	EM1WidgetAnimDirection                        InDirection;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InvasionDungeon_TimeAttack.UI_Game_InvasionDungeon_TimeAttack_C.ExecuteUbergraph_UI_Game_InvasionDungeon_TimeAttack
// 0x0070 (0x0070 - 0x0000)
struct UI_Game_InvasionDungeon_TimeAttack_C_ExecuteUbergraph_UI_Game_InvasionDungeon_TimeAttack final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bVisible;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable;                              // 0x000C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x001C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_2;                            // 0x002C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_struct_Variable_3;                            // 0x003C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1WidgetAnimDirection                        K2Node_Event_InDirection;                          // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_InUniqueId;                           // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayUIAnimation_ReturnValue;              // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0060(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InvasionDungeon_TimeAttack.UI_Game_InvasionDungeon_TimeAttack_C.BP_SetOpacityToOne
// 0x0001 (0x0001 - 0x0000)
struct UI_Game_InvasionDungeon_TimeAttack_C_BP_SetOpacityToOne final
{
public:
	bool                                          bVisible;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InvasionDungeon_TimeAttack.UI_Game_InvasionDungeon_TimeAttack_C.BP_ChangeActiveTimeAttack
// 0x0004 (0x0004 - 0x0000)
struct UI_Game_InvasionDungeon_TimeAttack_C_BP_ChangeActiveTimeAttack final
{
public:
	int32                                         InUniqueId;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_Game_InvasionDungeon_TimeAttack.UI_Game_InvasionDungeon_TimeAttack_C.BP_GetTimeAttackItems
// 0x0020 (0x0020 - 0x0000)
struct UI_Game_InvasionDungeon_TimeAttack_C_BP_GetTimeAttackItems final
{
public:
	TArray<class UM1UIInvasionDungeonScoreItem*>  ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, ContainsInstancedReference)
	TArray<class UM1UIInvasionDungeonScoreItem*>  K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
};

}

