#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_GameHP_Boss_Phase

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_GameHP_Boss_Phase.UI_GameHP_Boss_Phase_C.PlayFillOrEmpty
// 0x0020 (0x0020 - 0x0000)
struct UI_GameHP_Boss_Phase_C_PlayFillOrEmpty final
{
public:
	bool                                          bFill;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetEndTime_ReturnValue;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationTimeRange_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetEndTime_ReturnValue_1;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationTimeRange_ReturnValue_1;     // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function UI_GameHP_Boss_Phase.UI_GameHP_Boss_Phase_C.PlayCompleteAnim
// 0x0008 (0x0008 - 0x0000)
struct UI_GameHP_Boss_Phase_C_PlayCompleteAnim final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

}

