#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Game_MonsterInfos

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Game_MonsterInfos.UI_Game_MonsterInfos_C
// 0x0010 (0x0758 - 0x0748)
class UUI_Game_MonsterInfos_C final : public UM1UIGameMonsterInfoPanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0748(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	ESlateVisibility                              EVisibility;                                       // 0x0750(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ForSkillMovie;                                     // 0x0751(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_UI_Game_MonsterInfos(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Game_MonsterInfos_C">();
	}
	static class UUI_Game_MonsterInfos_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Game_MonsterInfos_C>();
	}
};

}

