#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InteractionObject_Marker

#include "Basic.hpp"

#include "UI_InteractionObject_Marker_classes.hpp"
#include "UI_InteractionObject_Marker_parameters.hpp"


namespace SDK
{

// Function UI_InteractionObject_Marker.UI_InteractionObject_Marker_C.ChangeMarkerColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Box                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_InteractionObject_Marker_C::ChangeMarkerColor(uint8 Box)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_InteractionObject_Marker_C", "ChangeMarkerColor");

	Params::UI_InteractionObject_Marker_C_ChangeMarkerColor Parms{};

	Parms.Box = Box;

	UObject::ProcessEvent(Func, &Parms);
}

}

