#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ItemIcon_Perk_Node

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.SetFill
// 0x0005 (0x0005 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_SetFill final
{
public:
	bool                                          Fill_0;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.SetEnchantPreview
// 0x0001 (0x0001 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_SetEnchantPreview final
{
public:
	bool                                          InEnchantPreview;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.SetBgStyle
// 0x0001 (0x0001 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_SetBgStyle final
{
public:
	bool                                          ViewBgDeco;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.Set Effect
// 0x0005 (0x0005 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_Set_Effect final
{
public:
	bool                                          ViewEffect;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.ExecuteUbergraph_UI_ItemIcon_Perk_Node
// 0x0008 (0x0008 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_ExecuteUbergraph_UI_ItemIcon_Perk_Node final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.BP_TurnOn
// 0x0001 (0x0001 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_BP_TurnOn final
{
public:
	bool                                          bIsMaxLevel;                                       // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.BP_ShowGlowingEffect
// 0x0001 (0x0001 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_BP_ShowGlowingEffect final
{
public:
	bool                                          bShow;                                             // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.SetSize
// 0x0020 (0x0020 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_SetSize final
{
public:
	struct FVector2D                              Size;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_X;                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast; // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_ItemIcon_Perk_Node.UI_ItemIcon_Perk_Node_C.SetMax
// 0x0001 (0x0001 - 0x0000)
struct UI_ItemIcon_Perk_Node_C_SetMax final
{
public:
	bool                                          Max;                                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

