#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_Task_TargetListItem_Supply_Single

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Mission_Task_TargetListItem_Supply_Single.UI_Mission_Task_TargetListItem_Supply_Single_C
// 0x0018 (0x0740 - 0x0728)
class UUI_Mission_Task_TargetListItem_Supply_Single_C final : public UM1UITaskTargetListItem_Supply
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0728(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       AnimMore;                                          // 0x0730(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       AnimLess;                                          // 0x0738(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_Mission_Task_TargetListItem_Supply_Single(int32 EntryPoint);
	void BP_MoreThanAlertRate();
	void BP_LessThanAlertRate();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Mission_Task_TargetListItem_Supply_Single_C">();
	}
	static class UUI_Mission_Task_TargetListItem_Supply_Single_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Mission_Task_TargetListItem_Supply_Single_C>();
	}
};

}

