#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_Task_Destruction_HUDCenter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Mission_Task_Destruction_HUDCenter.UI_Mission_Task_Destruction_HUDCenter_C
// 0x0018 (0x0770 - 0x0758)
class UUI_Mission_Task_Destruction_HUDCenter_C final : public UM1UIMissionTaskGoal_Desturction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0758(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       UIAnim_Open;                                       // 0x0760(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUI_Mission_Task_TargetListItem_Destruction_Single_C* UI_Mission_Task_TargetListItem_Destruction_Single; // 0x0768(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnEventWidgetOpen(EM1WidgetAnimDirection InDirection);
	void OnEventWidgetClose(EM1WidgetAnimDirection InDirection);
	void ExecuteUbergraph_UI_Mission_Task_Destruction_HUDCenter(int32 EntryPoint);

	TArray<class UWidget*> BP_GetTargetListItems() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Mission_Task_Destruction_HUDCenter_C">();
	}
	static class UUI_Mission_Task_Destruction_HUDCenter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Mission_Task_Destruction_HUDCenter_C>();
	}
};

}

