#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MissionWave_Start

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_MissionWave_Start.UI_MissionWave_Start_C.PlayAnimOpenClose
// 0x0008 (0x0008 - 0x0000)
struct UI_MissionWave_Start_C_PlayAnimOpenClose final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// Function UI_MissionWave_Start.UI_MissionWave_Start_C.ExecuteUbergraph_UI_MissionWave_Start
// 0x0004 (0x0004 - 0x0000)
struct UI_MissionWave_Start_C_ExecuteUbergraph_UI_MissionWave_Start final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function UI_MissionWave_Start.UI_MissionWave_Start_C.GetEndAnimation
// 0x0008 (0x0008 - 0x0000)
struct UI_MissionWave_Start_C_GetEndAnimation final
{
public:
	class UWidgetAnimation*                       ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};

}

