#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_EliteAbilityDetails_Items

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Mission_EliteAbilityDetails_Items.UI_Mission_EliteAbilityDetails_Items_C
// 0x0040 (0x0AA0 - 0x0A60)
class UUI_Mission_EliteAbilityDetails_Items_C final : public UM1UIEliteMonsterAbilities
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A60(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UM1TextBlock*                           Text_EliteLabel;                                   // 0x0A68(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_EliteAbilityDetails_Item_C* UI_Mission_EliteAbilityDetails_Item;               // 0x0A70(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_EliteAbilityDetails_Item_C* UI_Mission_EliteAbilityDetails_Item_1;             // 0x0A78(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_EliteAbilityDetails_Item_C* UI_Mission_EliteAbilityDetails_Item_2;             // 0x0A80(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_EliteAbilityDetails_Item_C* UI_Mission_EliteAbilityDetails_Item_3;             // 0x0A88(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_EliteAbilityDetails_Item_C* UI_Mission_EliteAbilityDetails_Item_4;             // 0x0A90(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Is_Label_Off;                                      // 0x0A98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Mission_EliteAbilityDetails_Items_C">();
	}
	static class UUI_Mission_EliteAbilityDetails_Items_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Mission_EliteAbilityDetails_Items_C>();
	}
};

}

