#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_Start

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "M1_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Mission_Start.UI_Mission_Start_C
// 0x0028 (0x0730 - 0x0708)
class UUI_Mission_Start_C final : public UM1UIChildMissionGuide
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0708(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_OpenClose;                                    // 0x0710(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UOverlay*                               MissionType;                                       // 0x0718(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UM1TextBlock*                           Text_Title;                                        // 0x0720(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UM1TextBlock*                           Text_Type;                                         // 0x0728(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void WidgetAnimationEvt_Anim_OpenClose_K2Node_WidgetAnimationEvent_0();
	void SetVisibleMissionText(bool bVisible);
	void SetVisibilityMissionType(bool InVisible);
	void SetMissionText(class FName MissionName, class FName MissionType_0);
	void SequenceEvent__ENTRYPOINTUI_Mission_Start();
	void PlayAnimOpenClose();
	void ExecuteUbergraph_UI_Mission_Start(int32 EntryPoint);
	void BP_widget_playAkEvent();

	class UWidgetAnimation* GetEndAnimation() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Mission_Start_C">();
	}
	static class UUI_Mission_Start_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Mission_Start_C>();
	}
};

}

