#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SubSkillIcon

#include "Basic.hpp"

#include "M1_structs.hpp"
#include "UI_SkillIcon_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_SubSkillIcon.UI_SubSkillIcon_C
// 0x0000 (0x08E8 - 0x08E8)
class UUI_SubSkillIcon_C final : public UUI_SkillIcon_C
{
public:
	bool                                          bReserved;                                         // 0x08E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTaggedActor;                                      // 0x08E2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1UIActionState                              ReserveIconState;                                  // 0x08E3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_SubSkillIcon_C">();
	}
	static class UUI_SubSkillIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_SubSkillIcon_C>();
	}
};

}

