#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SkillIconCustom_AJaxActive3

#include "Basic.hpp"

#include "UI_SkillIconCustom_AJaxActive3_classes.hpp"
#include "UI_SkillIconCustom_AJaxActive3_parameters.hpp"


namespace SDK
{

// Function UI_SkillIconCustom_AJaxActive3.UI_SkillIconCustom_AJaxActive3_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_SkillIconCustom_AJaxActive3_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_SkillIconCustom_AJaxActive3_C", "Tick");

	Params::UI_SkillIconCustom_AJaxActive3_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_SkillIconCustom_AJaxActive3.UI_SkillIconCustom_AJaxActive3_C.ExecuteUbergraph_UI_SkillIconCustom_AJaxActive3
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_SkillIconCustom_AJaxActive3_C::ExecuteUbergraph_UI_SkillIconCustom_AJaxActive3(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_SkillIconCustom_AJaxActive3_C", "ExecuteUbergraph_UI_SkillIconCustom_AJaxActive3");

	Params::UI_SkillIconCustom_AJaxActive3_C_ExecuteUbergraph_UI_SkillIconCustom_AJaxActive3 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

